[package]
name = "minidecaf"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
parser-macros = { git = "https://github.com/MashPlant/lalr1" }

[profile.dev.package."*"]
opt-level = 3